---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: true
  idempotency_test: true
  extra_vars: []

verifier:
  ruby_bindir: '/usr/bin'

platforms:
  - name: trusty64
    driver_config:
      box: ubuntu/trusty64
      box_url: https://atlas.hashicorp.com/ubuntu/trusty64

suites:
  - name: default
